### ISSUE TITLE
Release to NuGet

### ISSUE THREAD

**Issue by akarnokd** [reactor/reactor-core-dotnet#1]
Releasing to NuGet is trivial with **NuGet Package Explorer**. However, such releases require a NuGet private key. Since this is not my own project anymore, we should figure out how to release under a Reactor-banner to NuGet, i.e., I or @smaldini could perform the action.

**Comment by smaldini** [comment]
I can have a look but you're welcome to use a new one adapted for the project. We don't have another AFAIK.

**Comment by akarnokd** [comment]
The release works. https://www.nuget.org/packages/Reactor.Core/
