### ISSUE TITLE
Converting an RX observable to a publisher

### ISSUE THREAD

**Issue by SeanFarrow** [reactor/reactor-core-dotnet#4]
Hi,

Is there a way wit hReactor to convert an RX IObservable<T> to an IPublisher<t>?
Any help appreciated.
Kind regards
Sean.

**Comment by akarnokd** [comment]
Yes, add `using reactor.core` and given an IObservable, call `.ToFlux(BackpressureHandling.BUFFER)` on it. The resulting `IFlux` is an `IPublisher`.

**Comment by SeanFarrow** [comment]
Hi,

Brilliant, Cheers

**Comment by SeanFarrow** [comment]
Thanks for this, as an easier solution, is there a way of converting a .net custom event to an IPublisher? Essentially the situation I'm in is an external library calls a provided action, passing in two values which I'm wrapping in to my own class. I need to publish this class to subscribed consumers that expect an IPublisher. What would be the best way, whilst limiting dependencies?

**Comment by akarnokd** [comment]
I don't think so.

**Comment by SeanFarrow** [comment]
Hi,

Thanks David, that’s a pity!
